[build]
command = "npm run build && NODE_OPTIONS='--inspect'"
publish = ".next"
environment = { NODE_VERSION = "16.*" }





[[headers]]
for = "/_next/image/*"

[headers.values]
Strict-Transport-Security = "max-age=31536000"
X-Test = 'foobar'

[[plugins]]
package = "@netlify/plugin-nextjs"

# This is a fake plugin, that makes it run npm install

[[redirects]]
from = "/*"
to = "/index.html"
